default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DATABASE_POOL"] || 5 %>

development:
  <<: *default
  database: circleci_dev

test:
  <<: *default
  database: circleci_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
